config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'coaches#index'
  resources :users, only:[:edit, :update]
  resources :students do
    resources :comments, only: [:create, :delete]
  end
  resources :coaches do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create, :delete]
  end
end

app/models/student.rb
class Student < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :rank

  with_options presence: true do
    validates :rank_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :kill_rate
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :price
    validates :times_to_teach
    validates :enthusiasm_text
  end
  
  belongs_to :user
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:destroy]

  def index
    @students = Student.order("created_at DESC")
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    unless @student.user_id == current_user.id
      redirect_to students_path
    end
  end

  def update
    if @student.update(student_params)
      redirect_to student_path(student_params)
    else
      render :edit
    end
  end

  def destroy
    if @student.user_id == current_user.id
      @student.destroy
      redirect_to students_path
    else
      redirect_to root_path
    end
  end

  private

  def student_params
    params.require(:student).permit(:rank_id, :kill_rate, {:character => []}, :play_style, :play_time, {:play_device => []}, {:communication_tool => []}, :price, :times_to_teach, :enthusiasm_text).merge(user_id: current_user.id)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class="student-main">
        <h2 class="students-title">
        生徒情報変更<br>
        ご自身の情報を入力してください
        </h2>
        <%= form_with model: @student, local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

        <%# 生徒のランク %>
        <div class="student-rank">
          <div class="weight-bold-text">
            最高ランク
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:rank_id, Rank.all, :id, :name, {}, {class:"select-box", id:"highest-rank"}) %>
        </div>
        <%# 生徒のランク %>

        <%# キルレート %>
        <div class="student-kill-rate">
          <div class="weight-bold-text">
            キルレート
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :kill_rate, class:"kill-rate", id:"kill-rate", placeholder:"1.0" ,maxlength:"4" %>
        </div>
        <%# キルレート %>

        <%# 使用キャラクター %>
        <div class="student-character">
          <div class="weight-bold-text">
            使用キャラクター
            <span class="indispensable">必須</span>
          </div>
          <div class="select-character">
            <% f.label :character %>
              <%= f.check_box :character, {multiple: true}, "アッシュ", nil %>アッシュ<br>
              <%= f.check_box :character, {multiple: true}, "オクタン", nil %>オクタン<br>
              <%= f.check_box :character, {multiple: true}, "カタリスト", nil %>カタリスト<br>
              <%= f.check_box :character, {multiple: true}, "クリプト", nil %>クリプト<br>
              <%= f.check_box :character, {multiple: true}, "コンジット", nil %>コンジット<br>
              <%= f.check_box :character, {multiple: true}, "コースティック", nil %>コースティック<br>
              <%= f.check_box :character, {multiple: true}, "シア", nil %>シア<br>
              <%= f.check_box :character, {multiple: true}, "ジブラルタル", nil %>ジブラルタル<br>
              <%= f.check_box :character, {multiple: true}, "ニューキャッスル", nil %>ニューキャッスル<br>
              <%= f.check_box :character, {multiple: true}, "バリスティック", nil %>バリスティック<br>
              <%= f.check_box :character, {multiple: true}, "バンガロール", nil %>バンガロール<br>
              <%= f.check_box :character, {multiple: true}, "パスファインダー", nil %>パスファインダー<br>
              <%= f.check_box :character, {multiple: true}, "ヒューズ", nil %>ヒューズ<br>
              <%= f.check_box :character, {multiple: true}, "ブラッドハウンド", nil %>ブラッドハウンド<br>
              <%= f.check_box :character, {multiple: true}, "ホライゾン", nil %>ホライゾン<br>
              <%= f.check_box :character, {multiple: true}, "マッドマギー", nil %>マッドマギー<br>
              <%= f.check_box :character, {multiple: true}, "ミラージュ", nil %>ミラージュ<br>
              <%= f.check_box :character, {multiple: true}, "ライフライン", nil %>ライフライン<br>
              <%= f.check_box :character, {multiple: true}, "ランパート", nil %>ランパート<br>
              <%= f.check_box :character, {multiple: true}, "レイス", nil %>レイス<br>
              <%= f.check_box :character, {multiple: true}, "レヴナント", nil %>レヴナント<br>
              <%= f.check_box :character, {multiple: true}, "ローバ", nil %>ローバ<br>
              <%= f.check_box :character, {multiple: true}, "ワットソン", nil %>ワットソン<br>
              <%= f.check_box :character, {multiple: true}, "ヴァルキリー", nil %>ヴァルキリー<br>
              <%= f.check_box :character, {multiple: true}, "ヴァンテージ", nil %>ヴァンテージ<br>
          </div>
        </div>
        <%# 使用キャラクター %>

        <%# プレイスタイル %>
        <div class="play-style">
          <div class="weight-bold-text">
            プレイスタイル
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :play_style, class:"play-style-text", id:"play-style", placeholder:"音の鳴る方へ" %>
        </div>
        <%# プレイスタイル %>

        <%# プレイ時間帯 %>
        <div class="play-time">
          <div class="weight-bold-text">
            プレイ時間帯
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :play_time, class:"play-time-text", id:"play-time", placeholder:"22時～24時" %>
        </div>
        <%# プレイ時間帯 %>

        <%# 使用デバイス %>
        <div class="play-device">
          <div class="weight-bold-text">
            プラットフォーム
            <span class="indispensable">必須</span>
          </div>
          <div class="select-device">
            <% f.label :play_device %>
              <%= f.check_box :play_device, {multiple: true}, "PC", nil %>PC<br>
              <%= f.check_box :play_device, {multiple: true}, "PS4/PS5", nil %>PS4/PS5<br>
              <%= f.check_box :play_device, {multiple: true}, "Xbox", nil %>Xbox<br>
              <%= f.check_box :play_device, {multiple: true}, "Switch", nil %>Switch<br>

          </div>
        </div>
        <%# 使用デバイス %>

        <%# コミュニケーションツール %>
        <div class="communication-tool">
          <div class="weight-bold-text">
            コミュニケーションツール
            <span class="indispensable">必須</span>
          </div>
          <div class="select-tool">
            <% f.label :communication_tool %>
              <%= f.check_box :communication_tool, {multiple: true}, "Discord", nil %>Discord<br>
              <%= f.check_box :communication_tool, {multiple: true}, "Skype", nil %>Skype<br>
              <%= f.check_box :communication_tool, {multiple: true}, "LINE", nil %>LINE<br>
              <%= f.check_box :communication_tool, {multiple: true}, "OpenVC", nil %>OpenVC<br>
              <%= f.check_box :communication_tool, {multiple: true}, "PS4/PS5", nil %>PS4/PS5<br>
              <%= f.check_box :communication_tool, {multiple: true}, "Switch", nil %>Switch<br>
          </div>
        </div>
        <%# コミュニケーションツール %>

        <%# 希望コーチング回数 %>
        <div class="student-character">
          <div class="weight-bold-text">
            希望コーチング回数
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :times_to_teach, class:"times-to-teach-text", id:"times-to-teach", placeholder:"3" %>
          <span class="sell-yen">回</span>
        </div>
        <%# 希望コーチング回数 %>

        <%# 予算 %>
        <div class="student-character">
          <div class="weight-bold-text">
            予算
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price", id:"price", placeholder:"3000" %>
        </div>
        <%# 予算 %>

        <%# 意気込み %>
        <div class="student-character">
          <div class="weight-bold-text">
            意気込み
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :enthusiasm_text, class: "enthusiasm-text", id: "enthusiasm", placeholder:"精一杯頑張ります", maxlength:"100" %>
        </div>
        <%# 意気込み %>

        <div class="register-btn-contents">
          <%= f.submit "変更する", method: :get, class:"register-btn" %>
          <%=link_to 'やめる', root_path, class:"back-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/students/index.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class="student-main">
        <% @students.each do |student| %>
          <%= link_to student_path(student) do %>
          <div class='student-info'>
            <div class='student-nickname'>
              <span>生徒名：<%= student.user.nickname %></span>
            </div>
            <div class='students-info'>
              <span>生徒の最高ランク　　　　：<%= student.rank.name %></span><br>
              <span>プレイ時間帯　　　　　　：<%= student.play_time %></span><br>
              <span>プラットフォーム　　　　：<%= student.play_device %></span><br>
              <span>コミュニケーションツール：<%= student.communication_tool %></span><br>
              <span>希望コーチング回数　　　：<%= student.times_to_teach %>回</span><br>
              <span>予算　　　　　　　　　　：<%= student.price %>円</span><br>
              <span>意気込み　　　　　　　　：<%= student.enthusiasm_text %></span>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/students/new.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class="student-main">
        <h2 class="students-title">
        生徒情報登録<br>
        ご自身の情報を入力してください
        </h2>
        <%= form_with model: @student, local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

        <%# 生徒のランク %>
        <div class="student-rank">
          <div class="weight-bold-text">
            最高ランク
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:rank_id, Rank.all, :id, :name, {}, {class:"select-box", id:"highest-rank"}) %>
        </div>
        <%# 生徒のランク %>

        <%# キルレート %>
        <div class="student-kill-rate">
          <div class="weight-bold-text">
            キルレート
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :kill_rate, class:"kill-rate", id:"kill-rate", placeholder:"1.0" ,maxlength:"4" %>
        </div>
        <%# キルレート %>

        <%# 使用キャラクター %>
        <div class="student-character">
          <div class="weight-bold-text">
            使用キャラクター
            <span class="indispensable">必須</span>
          </div>
          <div class="select-character">
            <% f.label :character %>
              <%= f.check_box :character, {multiple: true}, "アッシュ", nil %>アッシュ<br>
              <%= f.check_box :character, {multiple: true}, "オクタン", nil %>オクタン<br>
              <%= f.check_box :character, {multiple: true}, "カタリスト", nil %>カタリスト<br>
              <%= f.check_box :character, {multiple: true}, "クリプト", nil %>クリプト<br>
              <%= f.check_box :character, {multiple: true}, "コンジット", nil %>コンジット<br>
              <%= f.check_box :character, {multiple: true}, "コースティック", nil %>コースティック<br>
              <%= f.check_box :character, {multiple: true}, "シア", nil %>シア<br>
              <%= f.check_box :character, {multiple: true}, "ジブラルタル", nil %>ジブラルタル<br>
              <%= f.check_box :character, {multiple: true}, "ニューキャッスル", nil %>ニューキャッスル<br>
              <%= f.check_box :character, {multiple: true}, "バリスティック", nil %>バリスティック<br>
              <%= f.check_box :character, {multiple: true}, "バンガロール", nil %>バンガロール<br>
              <%= f.check_box :character, {multiple: true}, "パスファインダー", nil %>パスファインダー<br>
              <%= f.check_box :character, {multiple: true}, "ヒューズ", nil %>ヒューズ<br>
              <%= f.check_box :character, {multiple: true}, "ブラッドハウンド", nil %>ブラッドハウンド<br>
              <%= f.check_box :character, {multiple: true}, "ホライゾン", nil %>ホライゾン<br>
              <%= f.check_box :character, {multiple: true}, "マッドマギー", nil %>マッドマギー<br>
              <%= f.check_box :character, {multiple: true}, "ミラージュ", nil %>ミラージュ<br>
              <%= f.check_box :character, {multiple: true}, "ライフライン", nil %>ライフライン<br>
              <%= f.check_box :character, {multiple: true}, "ランパート", nil %>ランパート<br>
              <%= f.check_box :character, {multiple: true}, "レイス", nil %>レイス<br>
              <%= f.check_box :character, {multiple: true}, "レヴナント", nil %>レヴナント<br>
              <%= f.check_box :character, {multiple: true}, "ローバ", nil %>ローバ<br>
              <%= f.check_box :character, {multiple: true}, "ワットソン", nil %>ワットソン<br>
              <%= f.check_box :character, {multiple: true}, "ヴァルキリー", nil %>ヴァルキリー<br>
              <%= f.check_box :character, {multiple: true}, "ヴァンテージ", nil %>ヴァンテージ<br>
          </div>
        </div>
        <%# 使用キャラクター %>

        <%# プレイスタイル %>
        <div class="play-style">
          <div class="weight-bold-text">
            プレイスタイル
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :play_style, class:"play-style-text", id:"play-style", placeholder:"音の鳴る方へ" %>
        </div>
        <%# プレイスタイル %>

        <%# プレイ時間帯 %>
        <div class="play-time">
          <div class="weight-bold-text">
            プレイ時間帯
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :play_time, class:"play-time-text", id:"play-time", placeholder:"22時～24時" %>
        </div>
        <%# プレイ時間帯 %>

        <%# 使用デバイス %>
        <div class="play-device">
          <div class="weight-bold-text">
            プラットフォーム
            <span class="indispensable">必須</span>
          </div>
          <div class="select-device">
            <% f.label :play_device %>
              <%= f.check_box :play_device, {multiple: true}, "PC", nil %>PC<br>
              <%= f.check_box :play_device, {multiple: true}, "PS4/PS5", nil %>PS4/PS5<br>
              <%= f.check_box :play_device, {multiple: true}, "Xbox", nil %>Xbox<br>
              <%= f.check_box :play_device, {multiple: true}, "Switch", nil %>Switch<br>

          </div>
        </div>
        <%# 使用デバイス %>

        <%# コミュニケーションツール %>
        <div class="communication-tool">
          <div class="weight-bold-text">
            コミュニケーションツール
            <span class="indispensable">必須</span>
          </div>
          <div class="select-tool">
            <% f.label :communication_tool %>
              <%= f.check_box :communication_tool, {multiple: true}, "Discord", nil %>Discord<br>
              <%= f.check_box :communication_tool, {multiple: true}, "Skype", nil %>Skype<br>
              <%= f.check_box :communication_tool, {multiple: true}, "LINE", nil %>LINE<br>
              <%= f.check_box :communication_tool, {multiple: true}, "OpenVC", nil %>OpenVC<br>
              <%= f.check_box :communication_tool, {multiple: true}, "PS4/PS5", nil %>PS4/PS5<br>
              <%= f.check_box :communication_tool, {multiple: true}, "Switch", nil %>Switch<br>
          </div>
        </div>
        <%# コミュニケーションツール %>

        <%# 希望コーチング回数 %>
        <div class="student-character">
          <div class="weight-bold-text">
            希望コーチング回数
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :times_to_teach, class:"times-to-teach-text", id:"times-to-teach", placeholder:"3" %>
          <span class="sell-yen">回</span>
        </div>
        <%# 希望コーチング回数 %>

        <%# 予算 %>
        <div class="student-character">
          <div class="weight-bold-text">
            予算
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price", id:"price", placeholder:"3000" %>
        </div>
        <%# 予算 %>

        <%# 意気込み %>
        <div class="student-character">
          <div class="weight-bold-text">
            意気込み
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :enthusiasm_text, class: "enthusiasm-text", id: "enthusiasm", placeholder:"精一杯頑張ります", maxlength:"100" %>
        </div>
        <%# 意気込み %>

        <div class="register-btn-contents">
          <%= f.submit "登録する", method: :get, class: "register-btn" %>
          <%= link_to "やめる", root_path, class: "back-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/students/show.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class='student-info'>
        <h2 class='student-detail'>
          生徒情報詳細
        </h2>
        <div class='studenting-detail'>
          <span>生徒名　　　　　　　　　：<%= @student.user.nickname %></span><br>
          <span>生徒の最高ランク　　　　：<%= @student.rank.name %></span><br>
          <span>キルレート　　　　　　　：<%= @student.kill_rate %></span><br>
          <span>キャラクター　　　　　　：<%= @student.character %></span><br>
          <span>プレイスタイル　　　　　：<%= @student.play_style %></span><br>
          <span>プレイ時間帯　　　　　　：<%= @student.play_time %></span><br>
          <span>プラットフォーム　　　　：<%= @student.play_device %></span><br>
          <span>コミュニケーションツール：<%= @student.communication_tool %></span><br>
          <span>希望コーチング回数　　　：<%= @student.times_to_teach %>回</span><br>
          <span>予算　　　　　　　　　　：<%= @student.price %>円</span><br>
          <span>意気込み　　　　　　　　：<%= @student.enthusiasm_text %></span>
        </div>
      </div>
      
      <% if current_user == @student.user %>
        <%# unless @student.order.present? %>
          <div class="btn">
            <%= link_to "生徒情報の編集", edit_student_path(@student), method: :get, class: "student-edit-btn" %>
            <%= button_to "削除", '#', method: :delete, class:"student-destroy-btn" %>
          </div>
        <%# end %>
      <% elsif user_signed_in? %>
        <%# unless @student.order.present? %>
        <%= link_to "コメント", student_comments_path(@student), method: :get, class:"student-comment-btn"%>
        <%# end %>
      <% end %>
    </div>
  <%= render "shared/footer" %>
</div>