config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'coaches#index'
  resources :users, only:[:edit, :update]
  resources :students do
    resources :comments, only: [:create, :delete]
  end
  resources :coaches do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create, :delete]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :rank
  belongs_to :rank_limit

  with_options presence: true do
    validates :rank_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :kill_rate
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :price
    validates :times_to_teach
    validates :rank_limit_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :appeal_point
  end
  
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :coach
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :coach
  has_one :payment
end

app/models/order_form.rb
class OrderForm
  include ActiveModel::Model
  attr_accessor :user_id, :coach_id, :rank_id, :character, :play_style, :play_time, :play_device, :communication_tool, :goal, :token

  with_options presence: true do
    validates :user_id
    validates :coach_id

    validates :rank_id
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :goal

    validates :token
  end

  def save
    order = Order.create(user_id: user_id, coach_id: coach_id)
    Payment.create(coach_id: coach_id, order_id: order.id, rank_id: rank_id, character: character, play_style: play_style, play_time: play_time, play_device: play_device, communication_tool: communication_tool, goal: goal)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/rank.rb
class Rank < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ルーキー' },
    { id: 3, name: 'ブロンズⅣ' },
    { id: 4, name: 'ブロンズⅢ' },
    { id: 5, name: 'ブロンズⅡ' },
    { id: 6, name: 'ブロンズⅠ' },
    { id: 7, name: 'シルバーⅣ' },
    { id: 8, name: 'シルバーⅢ' },
    { id: 9, name: 'シルバーⅡ' },
    { id: 10, name: 'シルバーⅠ' },
    { id: 11, name: 'ゴールドⅣ' },
    { id: 12, name: 'ゴールドⅢ' },
    { id: 13, name: 'ゴールドⅡ' },
    { id: 14, name: 'ゴールドⅠ' },
    { id: 15, name: 'プラチナⅣ' },
    { id: 16, name: 'プラチナⅢ' },
    { id: 17, name: 'プラチナⅡ' },
    { id: 18, name: 'プラチナⅠ' },
    { id: 19, name: 'ダイヤⅣ' },
    { id: 20, name: 'ダイヤⅢ' },
    { id: 21, name: 'ダイヤⅡ' },
    { id: 22, name: 'ダイヤⅠ' },
    { id: 23, name: 'マスター' },
    { id: 24, name: 'プレデター' }
  ]

  include ActiveHash::Associations
  has_many :coaches
  has_many :students
end

app/models/rank_limit.rb
class RankLimit < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ルーキー' },
    { id: 3, name: 'ブロンズⅣ' },
    { id: 4, name: 'ブロンズⅢ' },
    { id: 5, name: 'ブロンズⅡ' },
    { id: 6, name: 'ブロンズⅠ' },
    { id: 7, name: 'シルバーⅣ' },
    { id: 8, name: 'シルバーⅢ' },
    { id: 9, name: 'シルバーⅡ' },
    { id: 10, name: 'シルバーⅠ' },
    { id: 11, name: 'ゴールドⅣ' },
    { id: 12, name: 'ゴールドⅢ' },
    { id: 13, name: 'ゴールドⅡ' },
    { id: 14, name: 'ゴールドⅠ' },
    { id: 15, name: 'プラチナⅣ' },
    { id: 16, name: 'プラチナⅢ' },
    { id: 17, name: 'プラチナⅡ' },
    { id: 18, name: 'プラチナⅠ' },
    { id: 19, name: 'ダイヤⅣ' },
    { id: 20, name: 'ダイヤⅢ' },
    { id: 21, name: 'ダイヤⅡ' },
    { id: 22, name: 'ダイヤⅠ' },
    { id: 23, name: 'マスター' },
    { id: 24, name: 'プレデター' }
  ]

  include ActiveHash::Associations
  has_many :coaches
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :rank

  with_options presence: true do
    validates :rank_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :kill_rate
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :price
    validates :times_to_teach
    validates :enthusiasm_text
  end
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :game_name, presence: true

  has_many :coaches
  has_many :students
  has_many :orders
  has_many :comments
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(useparams)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchingGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.pay.jp/v2/pay.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_importmap_tags 'application' %>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yomogi&display=swap" rel="stylesheet">
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>© MATCHING GAME</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css #%>
<header class='header'>
  <div class='logo'>
    <%= link_to image_tag("matching-logo.png", class:"matching-icon"), "/" %>
  </div>
  <div class='nav'>
    <ul class='lists'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, edit_user_registration_path, class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <li><%= link_to 'コーチ登録', new_coach_path, class: "new-coach" %></li>
        <li><%= link_to '生徒登録', new_student_path, class: "new-student" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_side_bar.html.erb
<div class='side-bar'>
  <div class="coaches">
    <div class="coach-title">
      <%= link_to 'コーチ一覧', root_path, method: :get, class: "coach-list" %>
    </div>
  </div>
  <div class="students">
    <div class="student-title">
      <%= link_to '生徒一覧', students_index_path, method: :get, class: "student-list" %>
    </div>
  </div>
  <div class="rooms">
    <div class='room-title'>
      <%= link_to 'ルーム一覧', root_path, method: :get, class: "room-list" %>
    </div>
  </div>
</div>