config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'coaches#index'
  resources :users, only:[:edit, :update]
  resources :students do
    resources :comments, only: [:create, :delete]
  end
  resources :coaches do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create, :delete]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :rank
  belongs_to :rank_limit

  with_options presence: true do
    validates :rank_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :kill_rate
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :price
    validates :times_to_teach
    validates :rank_limit_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :appeal_point
  end
  
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :coach
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :coach
  has_one :payment
end

app/models/order_form.rb
class OrderForm
  include ActiveModel::Model
  attr_accessor :user_id, :coach_id, :rank_id, :character, :play_style, :play_time, :play_device, :communication_tool, :goal, :token

  with_options presence: true do
    validates :user_id
    validates :coach_id

    validates :rank_id
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :goal

    validates :token
  end

  def save
    order = Order.create(user_id: user_id, coach_id: coach_id)
    Payment.create(coach_id: coach_id, order_id: order.id, rank_id: rank_id, character: character, play_style: play_style, play_time: play_time, play_device: play_device, communication_tool: communication_tool, goal: goal)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/rank.rb
class Rank < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ルーキー' },
    { id: 3, name: 'ブロンズⅣ' },
    { id: 4, name: 'ブロンズⅢ' },
    { id: 5, name: 'ブロンズⅡ' },
    { id: 6, name: 'ブロンズⅠ' },
    { id: 7, name: 'シルバーⅣ' },
    { id: 8, name: 'シルバーⅢ' },
    { id: 9, name: 'シルバーⅡ' },
    { id: 10, name: 'シルバーⅠ' },
    { id: 11, name: 'ゴールドⅣ' },
    { id: 12, name: 'ゴールドⅢ' },
    { id: 13, name: 'ゴールドⅡ' },
    { id: 14, name: 'ゴールドⅠ' },
    { id: 15, name: 'プラチナⅣ' },
    { id: 16, name: 'プラチナⅢ' },
    { id: 17, name: 'プラチナⅡ' },
    { id: 18, name: 'プラチナⅠ' },
    { id: 19, name: 'ダイヤⅣ' },
    { id: 20, name: 'ダイヤⅢ' },
    { id: 21, name: 'ダイヤⅡ' },
    { id: 22, name: 'ダイヤⅠ' },
    { id: 23, name: 'マスター' },
    { id: 24, name: 'プレデター' }
  ]

  include ActiveHash::Associations
  has_many :coaches
  has_many :students
end

app/models/rank_limit.rb
class RankLimit < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ルーキー' },
    { id: 3, name: 'ブロンズⅣ' },
    { id: 4, name: 'ブロンズⅢ' },
    { id: 5, name: 'ブロンズⅡ' },
    { id: 6, name: 'ブロンズⅠ' },
    { id: 7, name: 'シルバーⅣ' },
    { id: 8, name: 'シルバーⅢ' },
    { id: 9, name: 'シルバーⅡ' },
    { id: 10, name: 'シルバーⅠ' },
    { id: 11, name: 'ゴールドⅣ' },
    { id: 12, name: 'ゴールドⅢ' },
    { id: 13, name: 'ゴールドⅡ' },
    { id: 14, name: 'ゴールドⅠ' },
    { id: 15, name: 'プラチナⅣ' },
    { id: 16, name: 'プラチナⅢ' },
    { id: 17, name: 'プラチナⅡ' },
    { id: 18, name: 'プラチナⅠ' },
    { id: 19, name: 'ダイヤⅣ' },
    { id: 20, name: 'ダイヤⅢ' },
    { id: 21, name: 'ダイヤⅡ' },
    { id: 22, name: 'ダイヤⅠ' },
    { id: 23, name: 'マスター' },
    { id: 24, name: 'プレデター' }
  ]

  include ActiveHash::Associations
  has_many :coaches
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :rank

  with_options presence: true do
    validates :rank_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :kill_rate
    validates :character
    validates :play_time
    validates :play_device
    validates :communication_tool
    validates :price
    validates :times_to_teach
    validates :enthusiasm_text
  end
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :game_name, presence: true

  has_many :coaches
  has_many :students
  has_many :orders
  has_many :comments
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:destroy]

  def index
    @coaches = Coach.order("created_at DESC")
  end

  def new
    @coach = Coach.new
  end

  def create
    @coach = Coach.new(coach_params)
    if @coach.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @coach.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    unless @coach.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    if @coach.update(coach_params)
      redirect_to coach_path(coach_params)
    else
      render :edit
    end
  end

  def destroy
    if @coach.user_id == current_user.id
      @coach.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def coach_params
    params.require(:coach).permit(:rank_id, :kill_rate, {:character => []}, :play_style, :play_time, {:play_device => []}, {:communication_tool => []}, :price, :times_to_teach, :rank_limit_id, :appeal_point).merge(user_id: current_user.id)
  end

  def set_coach
    @coach = Coach.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @coach = Coach.find(params[:coach_id])
    if @comment.save
      CommentChannel.broadcast_to @coach, { comment: @comment, user: @comment.user }
    end 
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, coach_id: params[:coach_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :non_matched_coach, only: [:index, :create]

  def index
    @order_form = OrderForm.new
  end

  def create
    @order_form = OrderForm.new(order_params)
    #binding.pry
    if @order_form.valid?
      match
      @order_form.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def order_params
    params.require(:order_form).permit(:rank_id, {:character => []}, :play_style, :play_time, {:play_device => []}, {:communication_tool => []}, :goal).merge(user_id: current_user.id, coach_id: params[:coach_id], token: params[:token])
  end

  def match
    Payjp.api_key = 'sk_test_d0d0e718d7b91dfeb4a1ffd4'
    Payjp::Charge.create(
      amount: @coach.price,
      card: order_params[:token],
      currency: 'jpy'
    )
  end

  def non_matched_coach
    @coach = Coach.find(params[:coach_id])
    if current_user.id == @coach.user_id
      redirect_to root_path
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(useparams)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coaches/edit.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class="coach-main">
        <h2 class="coaches-title">ご自身の情報を入力してください</h2>
        <%= form_with model: @coach, local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

        <%# コーチのランク %>
        <div class="coach-rank">
          <div class="weight-bold-text">
            最高ランク
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:rank_id, Rank.all, :id, :name, {}, {class:"select-box", id:"highest-rank"}) %>
        </div>
        <%# コーチのランク %>

        <%# キルレート %>
        <div class="coach-kill-rate">
          <div class="weight-bold-text">
            キルレート
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :kill_rate, class:"kill-rate", id:"kill-rate", placeholder:"1.0" ,maxlength:"4" %>
        </div>
        <%# キルレート %>

        <%# 使用キャラクター %>
        <div class="coach-character">
          <div class="weight-bold-text">
            使用キャラクター
            <span class="indispensable">必須</span>
          </div>
          <div class="select-character">
            <% f.label :character %>
              <%= f.check_box :character, {multiple: true}, "アッシュ", nil %>アッシュ<br>
              <%= f.check_box :character, {multiple: true}, "オクタン", nil %>オクタン<br>
              <%= f.check_box :character, {multiple: true}, "カタリスト", nil %>カタリスト<br>
              <%= f.check_box :character, {multiple: true}, "クリプト", nil %>クリプト<br>
              <%= f.check_box :character, {multiple: true}, "コースティック", nil %>コースティック<br>
              <%= f.check_box :character, {multiple: true}, "シア", nil %>シア<br>
              <%= f.check_box :character, {multiple: true}, "ジブラルタル", nil %>ジブラルタル<br>
              <%= f.check_box :character, {multiple: true}, "ニューキャッスル", nil %>ニューキャッスル<br>
              <%= f.check_box :character, {multiple: true}, "バンガロール", nil %>バンガロール<br>
              <%= f.check_box :character, {multiple: true}, "パスファインダー", nil %>パスファインダー<br>
              <%= f.check_box :character, {multiple: true}, "ヒューズ", nil %>ヒューズ<br>
              <%= f.check_box :character, {multiple: true}, "ブラッドハウンド", nil %>ブラッドハウンド<br>
              <%= f.check_box :character, {multiple: true}, "ホライゾン", nil %>ホライゾン<br>
              <%= f.check_box :character, {multiple: true}, "マッドマギー", nil %>マッドマギー<br>
              <%= f.check_box :character, {multiple: true}, "ミラージュ", nil %>ミラージュ<br>
              <%= f.check_box :character, {multiple: true}, "ライフライン", nil %>ライフライン<br>
              <%= f.check_box :character, {multiple: true}, "ランパート", nil %>ランパート<br>
              <%= f.check_box :character, {multiple: true}, "レイス", nil %>レイス<br>
              <%= f.check_box :character, {multiple: true}, "レヴナント", nil %>レヴナント<br>
              <%= f.check_box :character, {multiple: true}, "ローバ", nil %>ローバ<br>
              <%= f.check_box :character, {multiple: true}, "ワットソン", nil %>ワットソン<br>
              <%= f.check_box :character, {multiple: true}, "ヴァルキリー", nil %>ヴァルキリー<br>
              <%= f.check_box :character, {multiple: true}, "ヴァンテージ", nil %>ヴァンテージ<br>
          </div>
        </div>
        <%# 使用キャラクター %>

        <%# プレイスタイル %>
        <div class="play-style">
          <div class="weight-bold-text">
            プレイスタイル
          </div>
          <%= f.text_area :play_style, class:"play-style-text", id:"play-style", placeholder:"音の鳴る方へ" %>
        </div>
        <%# プレイスタイル %>

        <%# プレイ時間帯 %>
        <div class="play-time">
          <div class="weight-bold-text">
            プレイ時間帯
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :play_time, class:"play-time-text", id:"play-time", placeholder:"22時～24時" %>
        </div>
        <%# プレイ時間帯 %>

        <%# 使用デバイス %>
        <div class="play-device">
          <div class="weight-bold-text">
            プラットフォーム
            <span class="indispensable">必須</span>
          </div>
          <div class="select-device">
            <% f.label :play_device %>
              <%= f.check_box :play_device, {multiple: true}, "PC", nil %>PC<br>
              <%= f.check_box :play_device, {multiple: true}, "PS4/PS5", nil %>PS4/PS5<br>
              <%= f.check_box :play_device, {multiple: true}, "Xbox", nil %>Xbox<br>
              <%= f.check_box :play_device, {multiple: true}, "Switch", nil %>Switch<br>
              <%= f.check_box :play_device, {multiple: true}, "iOS", nil %>iOS<br>
              <%= f.check_box :play_device, {multiple: true}, "Android", nil %>Android<br>
          </div>
        </div>
        <%# 使用デバイス %>

        <%# コミュニケーションツール %>
        <div class="communication-tool">
          <div class="weight-bold-text">
            コミュニケーションツール
            <span class="indispensable">必須</span>
          </div>
          <div class="select-tool">
            <% f.label :communication_tool %>
              <%= f.check_box :communication_tool, {multiple: true}, "Discord", nil %>Discord<br>
              <%= f.check_box :communication_tool, {multiple: true}, "Skype", nil %>Skype<br>
              <%= f.check_box :communication_tool, {multiple: true}, "LINE", nil %>LINE<br>
              <%= f.check_box :communication_tool, {multiple: true}, "OpenVC", nil %>OpenVC<br>
              <%= f.check_box :communication_tool, {multiple: true}, "PS4/PS5", nil %>PS4/PS5<br>
              <%= f.check_box :communication_tool, {multiple: true}, "Switch", nil %>Switch<br>
          </div>
        </div>
        <%# コミュニケーションツール %>

        <%# コーチング回数 %>
        <div class="coach-character">
          <div class="weight-bold-text">
            コーチング回数
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :times_to_teach, class:"times-to-teach-text", id:"times-to-teach", placeholder:"3" %>
          <span class="sell-yen">回</span>
        </div>
        <%# コーチング回数 %>

        <%# コーチング料金 %>
        <div class="coach-character">
          <div class="weight-bold-text">
            コーチング料金
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price", id:"price", placeholder:"3000" %>
        </div>
        <%# コーチング料金 %>

        <%# 生徒のランク上限 %>
        <div class="coach-character">
          <div class="weight-bold-text">
            生徒のランク上限
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:rank_limit_id, RankLimit.all, :id, :name, {}, {class:"select-box", id:"rank-limit"}) %>
        </div>
        <%# 生徒のランク上限 %>

        <%# アピールポイント %>
        <div class="coach-character">
          <div class="weight-bold-text">
            アピールポイント
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :appeal_point, class:"appeal-point-text", id:"appeal-point", placeholder:"感度についてみっちり教えます", maxlength:"100" %>
        </div>
        <%# アピールポイント %>

        <div class="register-btn-contents">
          <%= f.submit "変更する", method: :get, class:"register-btn" %>
          <%=link_to 'やめる', root_path, class:"back-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/coaches/index.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class="coach-main">
        <% @coaches.each do |coach| %>
          <%= link_to coach_path(coach) do %>
          <div class='coach-info'>
            <div class='coach-nickname'>
              <span>コーチ名：<%= coach.user.nickname %></span>
            </div>
            <div class='coaching-info'>
              <span>コーチの最高ランク　　　：<%= coach.rank.name %></span><br>
              <span>プレイ時間帯　　　　　　：<%= coach.play_time %></span><br>
              <span>プラットフォーム　　　　：<%= coach.play_device %></span><br>
              <span>コミュニケーションツール：<%= coach.communication_tool %></span><br>
              <span>コーチング回数　　　　　：<%= coach.times_to_teach %>回</span><br>
              <span>価格　　　　　　　　　　：<%= coach.price %>円</span><br>
              <span>生徒のランク上限　　　　：<%= coach.rank_limit.name %></span><br>
              <span>アピールポイント　　　　：<%= coach.appeal_point %></span>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/coaches/show.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class='coach-info'>
        <h2 class='coaching-title'>
          コーチング内容詳細
        </h2>
        <div class='coaching-detail'>
          <span>コーチ名　　　　　　　　：<%= @coach.user.nickname %></span><br>
          <span>コーチの最高ランク　　　：<%= @coach.rank.name %></span><br>
          <span>キルレート　　　　　　　：<%= @coach.kill_rate %></span><br>
          <span>キャラクター　　　　　　：<%= @coach.character %></span><br>
          <span>プレイスタイル　　　　　：<%= @coach.play_style %></span><br>
          <span>プレイ時間帯　　　　　　：<%= @coach.play_time %></span><br>
          <span>プラットフォーム　　　　：<%= @coach.play_device %></span><br>
          <span>コミュニケーションツール：<%= @coach.communication_tool %></span><br>
          <span>コーチング回数　　　　　：<%= @coach.times_to_teach %>回</span><br>
          <span>価格　　　　　　　　　　：<%= @coach.price %>円</span><br>
          <span>生徒のランク上限　　　　：<%= @coach.rank_limit.name %></span><br>
          <span>アピールポイント　　　　：<%= @coach.appeal_point %></span>
        </div>
      </div>

      <% if current_user == @coach.user %>
        <%# unless @coach.order.present? %>
          <div class="btn">
            <%= link_to "コーチ情報の編集", edit_coach_path(@coach), method: :get, class: "coach-edit-btn" %>
            <%= button_to "削除", '#', method: :delete, class:"coach-destroy-btn" %>
          </div>
        <%# end %>
      <% elsif user_signed_in? %>
        <%# unless @coach.order.present? %>
        <%= link_to "購入画面に進む", coach_orders_path(@coach), method: :get, class:"coach-pay-btn"%>
        <%# end %>
      <% end %>

      <div class="comments">
        <h4>＜コメント一覧＞</h4>
          <% @coach.comments.each do |comment| %>
            <div class="comment">
              <p class="user-info"><%= comment.user.nickname %>： </p>
              <p><%= comment.text%></p>
            </div>
          <% end %>
      </div>

      <div class="comment-form">
        <% if user_signed_in? %>
          <%= form_with model: [@coach, @comment], id: "comment-form" do |f| %>
            <%= f.text_area :text , class: "comment-text"%>
            <%= f.submit "コメントをする", class: "comment-submit" %>
          <% end %>
        <% end %>
      </div>
      
    </div>
  <%= render "shared/footer" %>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
    <div class="side-bar">
      <%= render "shared/side_bar" %>
    </div>
    <div class="main">
      <div class="room-main">
      </div>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>